services:

  postgres:
    image: postgres:17
    container_name: olhovivo_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: olhovivo
      POSTGRES_USER: olhovivo
      POSTGRES_PASSWORD: olhovivo123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: olhovivo_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: olhovivo_backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - ./vision/output:/app/static/output
      - ./vision/videos:/app/static/videos

    depends_on:
      - postgres
      - redis

  vision:
    build: ./vision
    container_name: olhovivo_vision
    restart: unless-stopped

    volumes:
      - ./vision:/app
      - ./vision/output:/app/output

    depends_on:
      - backend

volumes:
  postgres_data:
